import { db } from "./db";
import { mooringLocations, type InsertMooringLocation } from "@shared/schema";

// Comprehensive UK Marine Facilities Database
// Covering England, Scotland, Wales and all islands with extensive jetty, pier, and marina coverage

const comprehensiveUKLocations: InsertMooringLocation[] = [
  // ENGLAND - South Coast Expansion
  {
    name: "Portsmouth Harbour",
    address: "Gunwharf Road, Portsmouth",
    county: "Hampshire",
    region: "South England",
    type: "marina",
    latitude: 50.7951,
    longitude: -1.1089,
    capacity: 180,
    depth: 4.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 23 9272 4811",
    email: "info@portsmouthharbour.co.uk",
    website: "www.portsmouthharbour.co.uk",
    description: "Historic naval port with modern marina facilities."
  },
  {
    name: "Dover Marina",
    address: "Granville Dock, Dover",
    county: "Kent",
    region: "Southeast England",
    type: "marina",
    latitude: 51.1289,
    longitude: 1.3186,
    capacity: 350,
    depth: 3.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 13 0420 3633",
    email: "info@dovermarina.com",
    website: "www.dovermarina.com",
    description: "Strategic location for cross-Channel sailing."
  },
  {
    name: "Weymouth Marina",
    address: "Commercial Road, Weymouth",
    county: "Dorset",
    region: "Southwest England",
    type: "marina",
    latitude: 50.6083,
    longitude: -2.4500,
    capacity: 520,
    depth: 2.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 13 0576 7576",
    email: "marina@weymouth-marina.co.uk",
    website: "www.weymouth-marina.co.uk",
    description: "Award-winning marina in beautiful Weymouth Bay."
  },
  {
    name: "Plymouth Mayflower Marina",
    address: "Richmond Walk, Plymouth",
    county: "Devon",
    region: "Southwest England",
    type: "marina",
    latitude: 50.3669,
    longitude: -4.1381,
    capacity: 420,
    depth: 3.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 17 5254 6688",
    email: "info@mayflowermarina.co.uk",
    website: "www.mayflowermarina.co.uk",
    description: "Historic marina in Britain's Ocean City."
  },
  {
    name: "Poole Quay Boat Haven",
    address: "Town Quay, Poole",
    county: "Dorset",
    region: "Southwest England",
    type: "marina",
    latitude: 50.7194,
    longitude: -1.9872,
    capacity: 140,
    depth: 1.8,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 12 0264 9488",
    email: "info@poolequayboathaven.co.uk",
    website: "www.poolequayboathaven.co.uk",
    description: "Central Poole location with excellent facilities."
  },
  {
    name: "Falmouth Marina",
    address: "North Parade, Falmouth",
    county: "Cornwall",
    region: "Southwest England",
    type: "marina",
    latitude: 50.1508,
    longitude: -5.0642,
    capacity: 400,
    depth: 4.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 13 2631 6620",
    email: "marina@falmouthport.co.uk",
    website: "www.falmouthport.co.uk",
    description: "Natural deep water harbour with excellent facilities."
  },
  {
    name: "Dartmouth Marina",
    address: "Mill Creek, Dartmouth",
    county: "Devon",
    region: "Southwest England",
    type: "marina",
    latitude: 50.3508,
    longitude: -3.5772,
    capacity: 320,
    depth: 3.2,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 18 0383 3351",
    email: "info@dartmouthmarina.com",
    website: "www.dartmouthmarina.com",
    description: "Sheltered marina on the beautiful River Dart."
  },
  {
    name: "Salcombe Harbour",
    address: "The Quay, Salcombe",
    county: "Devon",
    region: "Southwest England",
    type: "pier",
    latitude: 50.2386,
    longitude: -3.7694,
    capacity: 150,
    depth: 2.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 15 4854 4493",
    email: "harbourmaster@salcombe.gov.uk",
    website: "www.salcombeharbour.co.uk",
    description: "Beautiful natural harbour in South Devon."
  },
  {
    name: "Padstow Harbour",
    address: "The Harbour, Padstow",
    county: "Cornwall",
    region: "Southwest England",
    type: "pier",
    latitude: 50.5417,
    longitude: -4.9375,
    capacity: 80,
    depth: 2.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 18 4153 2239",
    email: "harbourmaster@padstow-tc.gov.uk",
    website: "www.padstow-tc.gov.uk",
    description: "Historic fishing port on Cornwall's north coast."
  },
  {
    name: "St Ives Harbour",
    address: "The Wharf, St Ives",
    county: "Cornwall",
    region: "Southwest England",
    type: "pier",
    latitude: 50.2142,
    longitude: -5.4839,
    capacity: 60,
    depth: 1.5,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 17 3679 5018",
    email: "harbourmaster@stives-tc.gov.uk",
    website: "www.stives-tc.gov.uk",
    description: "Picturesque harbour in the artists' town of St Ives."
  },
  {
    name: "Newlyn Harbour",
    address: "The Strand, Newlyn",
    county: "Cornwall",
    region: "Southwest England",
    type: "pier",
    latitude: 50.1028,
    longitude: -5.5428,
    capacity: 200,
    depth: 3.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 17 3636 2523",
    email: "harbourmaster@newlyn.harbour.co.uk",
    website: "www.newlyn.harbour.co.uk",
    description: "Cornwall's largest fishing port with modern facilities."
  },
  {
    name: "Fowey Harbour",
    address: "Town Quay, Fowey",
    county: "Cornwall",
    region: "Southwest England",
    type: "pier",
    latitude: 50.3358,
    longitude: -4.6361,
    capacity: 120,
    depth: 4.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 17 2683 2471",
    email: "harbourmaster@foweyharbour.co.uk",
    website: "www.foweyharbour.co.uk",
    description: "Deep water harbour on Cornwall's south coast."
  },
  {
    name: "Brixham Harbour",
    address: "The Strand, Brixham",
    county: "Devon",
    region: "Southwest England",
    type: "pier",
    latitude: 50.3944,
    longitude: -3.5150,
    capacity: 180,
    depth: 2.8,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 18 0385 3321",
    email: "harbourmaster@torbay.gov.uk",
    website: "www.brixhamharbour.co.uk",
    description: "Working fishing harbour in Torbay."
  },
  {
    name: "Ilfracombe Harbour",
    address: "The Quay, Ilfracombe",
    county: "Devon",
    region: "Southwest England",
    type: "pier",
    latitude: 51.2089,
    longitude: -4.1197,
    capacity: 90,
    depth: 2.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 12 7186 3001",
    email: "harbourmaster@northdevon.gov.uk",
    website: "www.northdevon.gov.uk",
    description: "Victorian harbour on North Devon coast."
  },
  {
    name: "Exmouth Marina",
    address: "The Strand, Exmouth",
    county: "Devon",
    region: "Southwest England",
    type: "marina",
    latitude: 50.6186,
    longitude: -3.4133,
    capacity: 250,
    depth: 2.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 13 9522 2184",
    email: "marina@exmouth-tc.gov.uk",
    website: "www.exmouthmarina.co.uk",
    description: "Marina at the mouth of the River Exe."
  },

  // ENGLAND - East Coast
  {
    name: "Lowestoft Marina",
    address: "Hamilton Dock, Lowestoft",
    county: "Suffolk",
    region: "East England",
    type: "marina",
    latitude: 52.4669,
    longitude: 1.7331,
    capacity: 380,
    depth: 3.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 15 0256 0631",
    email: "info@lowestoftmarina.co.uk",
    website: "www.lowestoftmarina.co.uk",
    description: "Modern marina in Britain's most easterly port."
  },
  {
    name: "Wells-next-the-Sea Harbour",
    address: "Beach Road, Wells-next-the-Sea",
    county: "Norfolk",
    region: "East England",
    type: "pier",
    latitude: 52.9667,
    longitude: 0.8500,
    capacity: 120,
    depth: 2.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 13 2871 0326",
    email: "harbourmaster@wells-harbour.co.uk",
    website: "www.wells-harbour.co.uk",
    description: "Charming harbour with mile-long road to the sea."
  },
  {
    name: "Yarmouth Marina",
    address: "South Quay, Great Yarmouth",
    county: "Norfolk",
    region: "East England",
    type: "marina",
    latitude: 52.6083,
    longitude: 1.7297,
    capacity: 200,
    depth: 3.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 14 9333 1051",
    email: "marina@great-yarmouth.gov.uk",
    website: "www.great-yarmouth.gov.uk",
    description: "Historic port with modern marina facilities."
  },
  {
    name: "Harwich Harbour",
    address: "The Quay, Harwich",
    county: "Essex",
    region: "East England",
    type: "pier",
    latitude: 51.9469,
    longitude: 1.2856,
    capacity: 160,
    depth: 4.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 12 5550 3429",
    email: "harbourmaster@harwich.gov.uk",
    website: "www.harwich.gov.uk",
    description: "Historic naval port and ferry terminal."
  },
  {
    name: "Burnham-on-Crouch Marina",
    address: "The Quay, Burnham-on-Crouch",
    county: "Essex",
    region: "East England",
    type: "marina",
    latitude: 51.6297,
    longitude: 0.8136,
    capacity: 340,
    depth: 2.8,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 16 2178 2150",
    email: "marina@burnhamyachtclub.co.uk",
    website: "www.burnhamyachtclub.co.uk",
    description: "Centre of east coast sailing with excellent facilities."
  },
  {
    name: "Ipswich Marina",
    address: "New Cut East, Ipswich",
    county: "Suffolk",
    region: "East England",
    type: "marina",
    latitude: 52.0497,
    longitude: 1.1631,
    capacity: 290,
    depth: 3.2,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 14 7321 5432",
    email: "info@ipswichmarina.co.uk",
    website: "www.ipswichmarina.co.uk",
    description: "Modern marina on the River Orwell."
  },

  // ENGLAND - North Coast
  {
    name: "Whitby Marina",
    address: "Langborne Road, Whitby",
    county: "North Yorkshire",
    region: "North England",
    type: "marina",
    latitude: 54.4858,
    longitude: -0.6153,
    capacity: 240,
    depth: 3.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 19 4760 2354",
    email: "marina@whitby.gov.uk",
    website: "www.whitby.gov.uk",
    description: "Historic harbour famous for Captain Cook and Dracula."
  },
  {
    name: "Scarborough Harbour",
    address: "Sandside, Scarborough",
    county: "North Yorkshire",
    region: "North England",
    type: "pier",
    latitude: 54.2767,
    longitude: -0.3953,
    capacity: 180,
    depth: 2.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 17 2337 3530",
    email: "harbourmaster@scarborough.gov.uk",
    website: "www.scarborough.gov.uk",
    description: "Victorian seaside resort with working harbour."
  },
  {
    name: "Bridlington Harbour",
    address: "Harbour Road, Bridlington",
    county: "East Yorkshire",
    region: "North England",
    type: "pier",
    latitude: 54.0844,
    longitude: -0.1933,
    capacity: 150,
    depth: 2.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 12 6267 3016",
    email: "harbourmaster@bridlington.gov.uk",
    website: "www.bridlington.gov.uk",
    description: "Traditional fishing harbour and seaside resort."
  },
  {
    name: "Hull Marina",
    address: "Hull Marina, Hull",
    county: "East Yorkshire",
    region: "North England",
    type: "marina",
    latitude: 53.7422,
    longitude: -0.3392,
    capacity: 270,
    depth: 4.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 14 8260 9899",
    email: "info@hullmarina.co.uk",
    website: "www.hullmarina.co.uk",
    description: "Modern marina in the heart of Hull."
  },
  {
    name: "Grimsby Marina",
    address: "Lock Hill, Grimsby",
    county: "Lincolnshire",
    region: "North England",
    type: "marina",
    latitude: 53.5681,
    longitude: -0.0847,
    capacity: 200,
    depth: 3.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 14 7235 6988",
    email: "marina@nelc.gov.uk",
    website: "www.nelc.gov.uk",
    description: "Historic fishing port with modern marina."
  },
  {
    name: "Boston Marina",
    address: "Witham Way, Boston",
    county: "Lincolnshire",
    region: "North England",
    type: "marina",
    latitude: 52.9781,
    longitude: -0.0261,
    capacity: 120,
    depth: 2.8,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 12 0536 2525",
    email: "marina@boston.gov.uk",
    website: "www.boston.gov.uk",
    description: "River marina in historic market town."
  },

  // SCOTLAND - West Coast Expansion
  {
    name: "Inveraray Harbour",
    address: "Front Street, Inveraray",
    county: "Argyll",
    region: "Scotland West",
    type: "pier",
    latitude: 56.2331,
    longitude: -5.0708,
    capacity: 40,
    depth: 3.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 14 9950 2172",
    email: "harbourmaster@inveraray.org.uk",
    website: "www.inveraray.org.uk",
    description: "Historic harbour on the shores of Loch Fyne."
  },
  {
    name: "Tarbert Harbour",
    address: "Harbour Street, Tarbert",
    county: "Argyll",
    region: "Scotland West",
    type: "pier",
    latitude: 55.8669,
    longitude: -5.4331,
    capacity: 80,
    depth: 4.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 18 8082 0344",
    email: "harbourmaster@tarbert.org.uk",
    website: "www.tarbert.org.uk",
    description: "Fishing harbour and gateway to the islands."
  },
  {
    name: "Campbeltown Harbour",
    address: "Old Quay Head, Campbeltown",
    county: "Argyll",
    region: "Scotland West",
    type: "pier",
    latitude: 55.4261,
    longitude: -5.6058,
    capacity: 120,
    depth: 5.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 15 8655 2552",
    email: "harbourmaster@campbeltown.org.uk",
    website: "www.campbeltown.org.uk",
    description: "Historic harbour at the tip of Kintyre peninsula."
  },
  {
    name: "Largs Marina",
    address: "Irvine Road, Largs",
    county: "North Ayrshire",
    region: "Scotland West",
    type: "marina",
    latitude: 55.7942,
    longitude: -4.8669,
    capacity: 750,
    depth: 2.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 14 7568 6666",
    email: "info@largs-marina.com",
    website: "www.largs-marina.com",
    description: "Scotland's largest marina on the Clyde coast."
  },
  {
    name: "Rothesay Harbour",
    address: "The Esplanade, Rothesay",
    county: "Argyll and Bute",
    region: "Scotland Islands",
    type: "pier",
    latitude: 55.8367,
    longitude: -5.0581,
    capacity: 100,
    depth: 3.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 17 0050 5151",
    email: "harbourmaster@argyll-bute.gov.uk",
    website: "www.argyll-bute.gov.uk",
    description: "Victorian resort harbour on the Isle of Bute."
  },
  {
    name: "Brodick Harbour",
    address: "Shore Road, Brodick",
    county: "North Ayrshire",
    region: "Scotland Islands",
    type: "pier",
    latitude: 55.5825,
    longitude: -5.1456,
    capacity: 60,
    depth: 4.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 17 7030 2169",
    email: "harbourmaster@north-ayrshire.gov.uk",
    website: "www.north-ayrshire.gov.uk",
    description: "Main ferry port for the Isle of Arran."
  },
  {
    name: "Millport Harbour",
    address: "Millport Pier, Cumbrae",
    county: "North Ayrshire",
    region: "Scotland Islands",
    type: "pier",
    latitude: 55.7547,
    longitude: -4.9286,
    capacity: 45,
    depth: 2.0,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 14 7553 0741",
    email: "harbourmaster@north-ayrshire.gov.uk",
    website: "www.north-ayrshire.gov.uk",
    description: "Small harbour on the island of Great Cumbrae."
  },

  // SCOTLAND - Highlands and Islands Expansion
  {
    name: "Mallaig Harbour",
    address: "Station Road, Mallaig",
    county: "Highland",
    region: "Scotland West",
    type: "pier",
    latitude: 57.0061,
    longitude: -5.8292,
    capacity: 140,
    depth: 6.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 16 8746 2154",
    email: "harbourmaster@highland.gov.uk",
    website: "www.highland.gov.uk",
    description: "Major fishing port and ferry terminal to the islands."
  },
  {
    name: "Kyle of Lochalsh Harbour",
    address: "Station Road, Kyle of Lochalsh",
    county: "Highland",
    region: "Scotland West",
    type: "pier",
    latitude: 57.2781,
    longitude: -5.7125,
    capacity: 80,
    depth: 4.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 15 9953 4167",
    email: "harbourmaster@highland.gov.uk",
    website: "www.highland.gov.uk",
    description: "Gateway to Skye with ferry connections."
  },
  {
    name: "Portree Harbour",
    address: "Quay Brae, Portree",
    county: "Highland",
    region: "Scotland Islands",
    type: "pier",
    latitude: 57.4131,
    longitude: -6.1947,
    capacity: 50,
    depth: 3.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 14 7861 2926",
    email: "harbourmaster@highland.gov.uk",
    website: "www.highland.gov.uk",
    description: "Capital of Skye with picturesque harbour."
  },
  {
    name: "Uig Harbour",
    address: "Ferry Road, Uig",
    county: "Highland",
    region: "Scotland Islands",
    type: "pier",
    latitude: 57.5825,
    longitude: -6.3708,
    capacity: 35,
    depth: 4.0,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 14 7054 2219",
    email: "harbourmaster@highland.gov.uk",
    website: "www.highland.gov.uk",
    description: "Ferry terminal on the Isle of Skye to the Outer Hebrides."
  },
  {
    name: "Armadale Harbour",
    address: "Ferry Pier, Armadale",
    county: "Highland",
    region: "Scotland Islands",
    type: "pier",
    latitude: 57.0706,
    longitude: -5.8983,
    capacity: 30,
    depth: 3.5,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 14 7184 4216",
    email: "harbourmaster@highland.gov.uk",
    website: "www.highland.gov.uk",
    description: "Ferry port connecting Skye to mainland Scotland."
  },
  {
    name: "Stornoway Harbour",
    address: "Esplanade, Stornoway",
    county: "Western Isles",
    region: "Scotland Islands",
    type: "marina",
    latitude: 58.2094,
    longitude: -6.3889,
    capacity: 120,
    depth: 5.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 18 5170 2688",
    email: "harbourmaster@cne-siar.gov.uk",
    website: "www.cne-siar.gov.uk",
    description: "Main port of the Outer Hebrides on Lewis."
  },
  {
    name: "Castlebay Harbour",
    address: "Main Street, Castlebay",
    county: "Western Isles",
    region: "Scotland Islands",
    type: "pier",
    latitude: 56.9583,
    longitude: -7.4869,
    capacity: 40,
    depth: 4.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 18 7181 0431",
    email: "harbourmaster@cne-siar.gov.uk",
    website: "www.cne-siar.gov.uk",
    description: "Ferry port and fishing harbour on the Isle of Barra."
  },
  {
    name: "Lochmaddy Harbour",
    address: "Ferry Terminal, Lochmaddy",
    county: "Western Isles",
    region: "Scotland Islands",
    type: "pier",
    latitude: 57.5986,
    longitude: -7.1606,
    capacity: 35,
    depth: 3.5,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 18 7650 0337",
    email: "harbourmaster@cne-siar.gov.uk",
    website: "www.cne-siar.gov.uk",
    description: "Ferry terminal on North Uist in the Outer Hebrides."
  },

  // SCOTLAND - East Coast and Northern Islands
  {
    name: "Lerwick Harbour",
    address: "Alexandra Wharf, Lerwick",
    county: "Shetland",
    region: "Scotland Islands",
    type: "marina",
    latitude: 60.1542,
    longitude: -1.1453,
    capacity: 150,
    depth: 8.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 15 9569 2991",
    email: "harbourmaster@shetland.gov.uk",
    website: "www.shetland.gov.uk",
    description: "Main port of the Shetland Islands with excellent facilities."
  },
  {
    name: "Kirkwall Harbour",
    address: "Ayre Road, Kirkwall",
    county: "Orkney",
    region: "Scotland Islands",
    type: "pier",
    latitude: 58.9828,
    longitude: -2.9606,
    capacity: 80,
    depth: 6.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 18 5687 2292",
    email: "harbourmaster@orkney.gov.uk",
    website: "www.orkney.gov.uk",
    description: "Capital of Orkney with historic harbour."
  },
  {
    name: "Stromness Harbour",
    address: "Victoria Street, Stromness",
    county: "Orkney",
    region: "Scotland Islands",
    type: "pier",
    latitude: 58.9581,
    longitude: -3.2981,
    capacity: 60,
    depth: 5.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 18 5685 0716",
    email: "harbourmaster@orkney.gov.uk",
    website: "www.orkney.gov.uk",
    description: "Historic harbour town on Orkney's west coast."
  },
  {
    name: "Aberdeen Marina",
    address: "Pocra Quay, Aberdeen",
    county: "Aberdeenshire",
    region: "Scotland East",
    type: "marina",
    latitude: 57.1436,
    longitude: -2.0803,
    capacity: 300,
    depth: 4.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 12 2458 7658",
    email: "marina@aberdeencity.gov.uk",
    website: "www.aberdeencity.gov.uk",
    description: "Modern marina in Scotland's granite city."
  },
  {
    name: "Peterhead Harbour",
    address: "Harbour Street, Peterhead",
    county: "Aberdeenshire",
    region: "Scotland East",
    type: "pier",
    latitude: 57.5042,
    longitude: -1.7847,
    capacity: 200,
    depth: 6.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 17 7947 4281",
    email: "harbourmaster@aberdeenshire.gov.uk",
    website: "www.aberdeenshire.gov.uk",
    description: "Major fishing port and oil industry base."
  },
  {
    name: "Fraserburgh Harbour",
    address: "Shore Street, Fraserburgh",
    county: "Aberdeenshire",
    region: "Scotland East",
    type: "pier",
    latitude: 57.6969,
    longitude: -2.0031,
    capacity: 180,
    depth: 5.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 13 4651 5858",
    email: "harbourmaster@aberdeenshire.gov.uk",
    website: "www.aberdeenshire.gov.uk",
    description: "Major fishing port in northeast Scotland."
  },

  // WALES - Comprehensive Coverage
  {
    name: "Milford Haven Marina",
    address: "Cleddau Bridge, Milford Haven",
    county: "Pembrokeshire",
    region: "West Wales",
    type: "marina",
    latitude: 51.7108,
    longitude: -5.0439,
    capacity: 230,
    depth: 5.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 16 4669 6969",
    email: "marina@pembrokeshire.gov.uk",
    website: "www.pembrokeshire.gov.uk",
    description: "Natural deep water harbour in West Wales."
  },
  {
    name: "Tenby Harbour",
    address: "Castle Hill, Tenby",
    county: "Pembrokeshire",
    region: "West Wales",
    type: "pier",
    latitude: 51.6722,
    longitude: -4.7003,
    capacity: 80,
    depth: 2.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 18 3484 2404",
    email: "harbourmaster@pembrokeshire.gov.uk",
    website: "www.pembrokeshire.gov.uk",
    description: "Medieval walled town with picturesque harbour."
  },
  {
    name: "Fishguard Harbour",
    address: "Goodwick, Fishguard",
    county: "Pembrokeshire",
    region: "West Wales",
    type: "pier",
    latitude: 52.0106,
    longitude: -4.9753,
    capacity: 100,
    depth: 8.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 13 4877 6226",
    email: "harbourmaster@pembrokeshire.gov.uk",
    website: "www.pembrokeshire.gov.uk",
    description: "Ferry port to Ireland with deep water berths."
  },
  {
    name: "Aberaeron Harbour",
    address: "Quay Parade, Aberaeron",
    county: "Ceredigion",
    region: "West Wales",
    type: "pier",
    latitude: 52.2406,
    longitude: -4.2619,
    capacity: 60,
    depth: 2.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 15 4557 0077",
    email: "harbourmaster@ceredigion.gov.uk",
    website: "www.ceredigion.gov.uk",
    description: "Colourful Georgian harbour town on Cardigan Bay."
  },
  {
    name: "Barmouth Harbour",
    address: "The Quay, Barmouth",
    county: "Gwynedd",
    region: "West Wales",
    type: "pier",
    latitude: 52.7208,
    longitude: -4.0503,
    capacity: 70,
    depth: 1.8,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 13 4128 0787",
    email: "harbourmaster@gwynedd.gov.uk",
    website: "www.gwynedd.gov.uk",
    description: "Resort town harbour at the mouth of the Mawddach estuary."
  },
  {
    name: "Pwllheli Marina",
    address: "South Beach, Pwllheli",
    county: "Gwynedd",
    region: "West Wales",
    type: "marina",
    latitude: 52.8831,
    longitude: -4.4169,
    capacity: 400,
    depth: 2.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 17 5861 3103",
    email: "marina@gwynedd.gov.uk",
    website: "www.gwynedd.gov.uk",
    description: "Major marina on the Lleyn Peninsula."
  },
  {
    name: "Caernarfon Harbour",
    address: "Slate Quay, Caernarfon",
    county: "Gwynedd",
    region: "North Wales",
    type: "pier",
    latitude: 53.1394,
    longitude: -4.2714,
    capacity: 90,
    depth: 3.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 12 8667 2601",
    email: "harbourmaster@gwynedd.gov.uk",
    website: "www.gwynedd.gov.uk",
    description: "Historic harbour beneath the walls of Caernarfon Castle."
  },
  {
    name: "Beaumaris Harbour",
    address: "Green Edge, Beaumaris",
    county: "Anglesey",
    region: "North Wales",
    type: "pier",
    latitude: 53.2633,
    longitude: -4.0917,
    capacity: 50,
    depth: 2.5,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 12 4881 0146",
    email: "harbourmaster@anglesey.gov.uk",
    website: "www.anglesey.gov.uk",
    description: "Historic harbour on the Menai Strait."
  },

  // ISLE OF WIGHT - Comprehensive Coverage
  {
    name: "Cowes Marina",
    address: "Medina Road, Cowes",
    county: "Isle of Wight",
    region: "South England",
    type: "marina",
    latitude: 50.7631,
    longitude: -1.2981,
    capacity: 370,
    depth: 2.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 19 8329 9975",
    email: "info@cowesmarina.com",
    website: "www.cowesmarina.com",
    description: "World-famous sailing centre and home of Cowes Week."
  },
  {
    name: "Yarmouth Harbour",
    address: "The Quay, Yarmouth",
    county: "Isle of Wight",
    region: "South England",
    type: "pier",
    latitude: 50.7058,
    longitude: -1.4981,
    capacity: 180,
    depth: 2.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 19 8376 0321",
    email: "harbourmaster@yarmouthharbour.co.uk",
    website: "www.yarmouthharbour.co.uk",
    description: "Historic harbour and ferry terminal on the Isle of Wight."
  },
  {
    name: "Bembridge Marina",
    address: "Embankment Road, Bembridge",
    county: "Isle of Wight",
    region: "South England",
    type: "marina",
    latitude: 50.6819,
    longitude: -1.0878,
    capacity: 280,
    depth: 1.8,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 19 8387 2828",
    email: "info@bembridgemarina.co.uk",
    website: "www.bembridgemarina.co.uk",
    description: "Sheltered marina on the east coast of the Isle of Wight."
  },
  {
    name: "Ryde Harbour",
    address: "The Esplanade, Ryde",
    county: "Isle of Wight",
    region: "South England",
    type: "pier",
    latitude: 50.7294,
    longitude: -1.1606,
    capacity: 120,
    depth: 1.5,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 19 8356 4896",
    email: "harbourmaster@iwight.com",
    website: "www.iwight.com",
    description: "Victorian seaside town with historic pier and harbour."
  },

  // ISLE OF MAN - Complete Coverage
  {
    name: "Douglas Harbour",
    address: "Loch Promenade, Douglas",
    county: "Isle of Man",
    region: "Isle of Man",
    type: "marina",
    latitude: 54.1500,
    longitude: -4.4775,
    capacity: 120,
    depth: 3.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 16 2468 6766",
    email: "harbourmaster@gov.im",
    website: "www.gov.im",
    description: "Main port of the Isle of Man with ferry connections."
  },
  {
    name: "Peel Harbour",
    address: "West Quay, Peel",
    county: "Isle of Man",
    region: "Isle of Man",
    type: "pier",
    latitude: 54.2275,
    longitude: -4.6978,
    capacity: 80,
    depth: 2.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 16 2484 2338",
    email: "harbourmaster@gov.im",
    website: "www.gov.im",
    description: "Historic fishing port with castle and cathedral."
  },
  {
    name: "Castletown Harbour",
    address: "Harbour Walk, Castletown",
    county: "Isle of Man",
    region: "Isle of Man",
    type: "pier",
    latitude: 54.0747,
    longitude: -4.6539,
    capacity: 60,
    depth: 2.0,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 16 2482 3308",
    email: "harbourmaster@gov.im",
    website: "www.gov.im",
    description: "Ancient capital with small harbour and marina."
  },
  {
    name: "Ramsey Harbour",
    address: "Parliament Street, Ramsey",
    county: "Isle of Man",
    region: "Isle of Man",
    type: "pier",
    latitude: 54.3214,
    longitude: -4.3839,
    capacity: 70,
    depth: 2.8,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 16 2481 2245",
    email: "harbourmaster@gov.im",
    website: "www.gov.im",
    description: "North coast harbour with good facilities."
  },
  {
    name: "Port St Mary Harbour",
    address: "Bay View Road, Port St Mary",
    county: "Isle of Man",
    region: "Isle of Man",
    type: "pier",
    latitude: 54.0694,
    longitude: -4.7333,
    capacity: 45,
    depth: 2.0,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 16 2483 2284",
    email: "harbourmaster@gov.im",
    website: "www.gov.im",
    description: "Small fishing harbour in the south of the island."
  },

  // SCOTTISH HIGHLANDS - Additional Coverage
  {
    name: "Ullapool Harbour",
    address: "Shore Street, Ullapool",
    county: "Highland",
    region: "Scotland North",
    type: "pier",
    latitude: 57.8953,
    longitude: -5.1608,
    capacity: 100,
    depth: 4.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 18 5461 2091",
    email: "harbourmaster@highland.gov.uk",
    website: "www.highland.gov.uk",
    description: "Ferry port to the Outer Hebrides and fishing harbour."
  },
  {
    name: "Gairloch Harbour",
    address: "Pier Road, Gairloch",
    county: "Highland",
    region: "Scotland North",
    type: "pier",
    latitude: 57.7128,
    longitude: -5.6908,
    capacity: 40,
    depth: 3.0,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 14 4571 2054",
    email: "harbourmaster@highland.gov.uk",
    website: "www.highland.gov.uk",
    description: "Small harbour in Wester Ross with beautiful scenery."
  },
  {
    name: "Scrabster Harbour",
    address: "Harbour Road, Scrabster",
    county: "Highland",
    region: "Scotland North",
    type: "pier",
    latitude: 58.6089,
    longitude: -3.5439,
    capacity: 80,
    depth: 6.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 18 4789 2779",
    email: "harbourmaster@highland.gov.uk",
    website: "www.highland.gov.uk",
    description: "Ferry port to Orkney Islands and fishing harbour."
  },

  // ISLAY AND INNER HEBRIDES - Comprehensive Coverage
  {
    name: "Port Ellen Harbour",
    address: "Port Ellen, Islay",
    county: "Argyll and Bute",
    region: "Scotland Islands",
    type: "pier",
    latitude: 55.6278,
    longitude: -6.1889,
    capacity: 60,
    depth: 4.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 14 9630 2209",
    email: "harbourmaster@argyll-bute.gov.uk",
    website: "www.argyll-bute.gov.uk",
    description: "Main ferry port for Islay, famous for whisky distilleries."
  },
  {
    name: "Port Askaig Harbour",
    address: "Port Askaig, Islay",
    county: "Argyll and Bute",
    region: "Scotland Islands",
    type: "pier",
    latitude: 55.8389,
    longitude: -6.1053,
    capacity: 40,
    depth: 5.0,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 14 9684 0232",
    email: "harbourmaster@argyll-bute.gov.uk",
    website: "www.argyll-bute.gov.uk",
    description: "Ferry terminal connecting Islay to Jura and mainland."
  },
  {
    name: "Bowmore Harbour",
    address: "Shore Street, Bowmore",
    county: "Argyll and Bute",
    region: "Scotland Islands",
    type: "pier",
    latitude: 55.7567,
    longitude: -6.2881,
    capacity: 25,
    depth: 2.5,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 14 9681 0671",
    email: "harbourmaster@argyll-bute.gov.uk",
    website: "www.argyll-bute.gov.uk",
    description: "Small harbour in Islay's capital town."
  },
  {
    name: "Craighouse Harbour",
    address: "Craighouse, Jura",
    county: "Argyll and Bute",
    region: "Scotland Islands",
    type: "pier",
    latitude: 55.8311,
    longitude: -5.9508,
    capacity: 20,
    depth: 3.0,
    hasFuel: false,
    hasWater: true,
    hasElectricity: false,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 14 9682 0243",
    email: "harbourmaster@argyll-bute.gov.uk",
    website: "www.argyll-bute.gov.uk",
    description: "Remote harbour on the island of Jura."
  },
  {
    name: "Colonsay Harbour",
    address: "Scalasaig, Colonsay",
    county: "Argyll and Bute",
    region: "Scotland Islands",
    type: "pier",
    latitude: 56.0575,
    longitude: -6.1831,
    capacity: 15,
    depth: 2.5,
    hasFuel: false,
    hasWater: true,
    hasElectricity: false,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 19 5120 0320",
    email: "harbourmaster@argyll-bute.gov.uk",
    website: "www.argyll-bute.gov.uk",
    description: "Small ferry terminal on remote Colonsay island."
  },

  // MULL AND SURROUNDING ISLANDS
  {
    name: "Tobermory Harbour",
    address: "Main Street, Tobermory",
    county: "Argyll and Bute",
    region: "Scotland Islands",
    type: "pier",
    latitude: 56.6231,
    longitude: -6.0669,
    capacity: 80,
    depth: 3.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 16 8830 2017",
    email: "harbourmaster@argyll-bute.gov.uk",
    website: "www.argyll-bute.gov.uk",
    description: "Picturesque harbour town on the Isle of Mull."
  },
  {
    name: "Craignure Harbour",
    address: "Craignure, Mull",
    county: "Argyll and Bute",
    region: "Scotland Islands",
    type: "pier",
    latitude: 56.4731,
    longitude: -5.7053,
    capacity: 50,
    depth: 4.0,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 16 8081 2343",
    email: "harbourmaster@argyll-bute.gov.uk",
    website: "www.argyll-bute.gov.uk",
    description: "Main ferry terminal for the Isle of Mull."
  },
  {
    name: "Iona Jetty",
    address: "Baile Mor, Iona",
    county: "Argyll and Bute",
    region: "Scotland Islands",
    type: "jetty",
    latitude: 56.3331,
    longitude: -6.4108,
    capacity: 12,
    depth: 2.0,
    hasFuel: false,
    hasWater: false,
    hasElectricity: false,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 16 8070 0512",
    email: "harbourmaster@argyll-bute.gov.uk",
    website: "www.argyll-bute.gov.uk",
    description: "Small jetty serving the sacred island of Iona."
  },
  {
    name: "Fionnphort Harbour",
    address: "Fionnphort, Mull",
    county: "Argyll and Bute",
    region: "Scotland Islands",
    type: "pier",
    latitude: 56.3256,
    longitude: -6.3731,
    capacity: 30,
    depth: 2.5,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 16 8170 0358",
    email: "harbourmaster@argyll-bute.gov.uk",
    website: "www.argyll-bute.gov.uk",
    description: "Ferry terminal to Iona on the Ross of Mull."
  },

  // TIREE AND COLL
  {
    name: "Scarinish Harbour",
    address: "Scarinish, Tiree",
    county: "Argyll and Bute",
    region: "Scotland Islands",
    type: "pier",
    latitude: 56.5003,
    longitude: -6.8731,
    capacity: 25,
    depth: 3.0,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 18 7922 0366",
    email: "harbourmaster@argyll-bute.gov.uk",
    website: "www.argyll-bute.gov.uk",
    description: "Ferry terminal on the island of Tiree."
  },
  {
    name: "Arinagour Harbour",
    address: "Arinagour, Coll",
    county: "Argyll and Bute",
    region: "Scotland Islands",
    type: "pier",
    latitude: 56.6178,
    longitude: -6.5531,
    capacity: 20,
    depth: 2.5,
    hasFuel: false,
    hasWater: true,
    hasElectricity: false,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 18 7923 0374",
    email: "harbourmaster@argyll-bute.gov.uk",
    website: "www.argyll-bute.gov.uk",
    description: "Small harbour on the remote island of Coll."
  },

  // SMALL ISLES - RUM, EIGG, MUCK, CANNA
  {
    name: "Kinloch Harbour",
    address: "Kinloch, Rum",
    county: "Highland",
    region: "Scotland Islands",
    type: "pier",
    latitude: 57.0089,
    longitude: -6.2839,
    capacity: 15,
    depth: 3.0,
    hasFuel: false,
    hasWater: true,
    hasElectricity: false,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 16 8746 2026",
    email: "harbourmaster@highland.gov.uk",
    website: "www.highland.gov.uk",
    description: "Small harbour on the Isle of Rum National Nature Reserve."
  },
  {
    name: "Galmisdale Harbour",
    address: "Galmisdale, Eigg",
    county: "Highland",
    region: "Scotland Islands",
    type: "pier",
    latitude: 56.9053,
    longitude: -6.1469,
    capacity: 12,
    depth: 2.5,
    hasFuel: false,
    hasWater: false,
    hasElectricity: false,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 16 8746 2277",
    email: "harbourmaster@highland.gov.uk",
    website: "www.highland.gov.uk",
    description: "Tiny harbour on the community-owned island of Eigg."
  },
  {
    name: "Port Mor Harbour",
    address: "Port Mor, Muck",
    county: "Highland",
    region: "Scotland Islands",
    type: "jetty",
    latitude: 56.8383,
    longitude: -6.2331,
    capacity: 8,
    depth: 2.0,
    hasFuel: false,
    hasWater: false,
    hasElectricity: false,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 16 8746 2365",
    email: "harbourmaster@highland.gov.uk",
    website: "www.highland.gov.uk",
    description: "Small jetty on the tiny island of Muck."
  },
  {
    name: "Canna Harbour",
    address: "Canna Harbour, Canna",
    county: "Highland",
    region: "Scotland Islands",
    type: "pier",
    latitude: 57.0531,
    longitude: -6.4889,
    capacity: 10,
    depth: 3.0,
    hasFuel: false,
    hasWater: false,
    hasElectricity: false,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 16 8746 2417",
    email: "harbourmaster@highland.gov.uk",
    website: "www.highland.gov.uk",
    description: "Remote harbour on the island of Canna."
  },

  // ADDITIONAL OUTER HEBRIDES
  {
    name: "Tarbert Harris Harbour",
    address: "Pier Road, Tarbert",
    county: "Western Isles",
    region: "Scotland Islands",
    type: "pier",
    latitude: 57.8981,
    longitude: -6.8069,
    capacity: 50,
    depth: 4.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 18 5950 2444",
    email: "harbourmaster@cne-siar.gov.uk",
    website: "www.cne-siar.gov.uk",
    description: "Ferry terminal between Harris and Uig on Skye."
  },
  {
    name: "Leverburgh Harbour",
    address: "Ferry Terminal, Leverburgh",
    county: "Western Isles",
    region: "Scotland Islands",
    type: "pier",
    latitude: 57.7769,
    longitude: -7.0331,
    capacity: 35,
    depth: 3.5,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 18 5950 2287",
    email: "harbourmaster@cne-siar.gov.uk",
    website: "www.cne-siar.gov.uk",
    description: "Ferry terminal to North Uist from Harris."
  },
  {
    name: "Lochboisdale Harbour",
    address: "Pier Road, Lochboisdale",
    county: "Western Isles",
    region: "Scotland Islands",
    type: "pier",
    latitude: 57.1331,
    longitude: -7.3089,
    capacity: 40,
    depth: 4.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: false,
    hasRestaurant: true,
    phone: "+44 18 7870 0244",
    email: "harbourmaster@cne-siar.gov.uk",
    website: "www.cne-siar.gov.uk",
    description: "Ferry port on South Uist to mainland Scotland."
  },

  // CHANNEL ISLANDS - Complete Coverage
  {
    name: "St Helier Marina",
    address: "South Pier, St Helier",
    county: "Jersey",
    region: "Channel Islands",
    type: "marina",
    latitude: 49.1831,
    longitude: -2.1069,
    capacity: 800,
    depth: 2.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 15 3444 7730",
    email: "harbours@gov.je",
    website: "www.gov.je",
    description: "Major marina in Jersey's capital with excellent facilities."
  },
  {
    name: "St Peter Port Marina",
    address: "North Beach, St Peter Port",
    county: "Guernsey",
    region: "Channel Islands",
    type: "marina",
    latitude: 49.4581,
    longitude: -2.5331,
    capacity: 340,
    depth: 3.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 14 8172 0229",
    email: "harbours@gov.gg",
    website: "www.gov.gg",
    description: "Beautiful marina in Guernsey's historic capital."
  },
  {
    name: "Alderney Harbour",
    address: "Braye Harbour, Alderney",
    county: "Alderney",
    region: "Channel Islands",
    type: "pier",
    latitude: 49.7269,
    longitude: -2.2031,
    capacity: 120,
    depth: 2.8,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 14 8182 2620",
    email: "harbours@alderney.gov.gg",
    website: "www.alderney.gov.gg",
    description: "Main harbour on the island of Alderney."
  },
  {
    name: "Sark Harbour",
    address: "Maseline Harbour, Sark",
    county: "Sark",
    region: "Channel Islands",
    type: "jetty",
    latitude: 49.4269,
    longitude: -2.3631,
    capacity: 30,
    depth: 2.0,
    hasFuel: false,
    hasWater: true,
    hasElectricity: false,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 14 8183 2345",
    email: "harbours@sark.gov.gg",
    website: "www.sark.gov.gg",
    description: "Small harbour on the car-free island of Sark."
  },

  // UK INLAND WATERWAYS - COMPREHENSIVE COVERAGE

  // THAMES RIVER SYSTEM
  {
    name: "Thames Barrier Marina",
    address: "Eastmoor Street, Charlton",
    county: "Greater London",
    region: "South England",
    type: "marina",
    latitude: 51.4847,
    longitude: 0.0169,
    capacity: 200,
    depth: 3.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 20 8858 7246",
    email: "info@thamesbarrierpark.org.uk",
    website: "www.thamesbarrierpark.org.uk",
    description: "Major Thames inland marina near the Thames Barrier."
  },
  {
    name: "Henley-on-Thames Marina",
    address: "Mill Lane, Henley-on-Thames",
    county: "Oxfordshire",
    region: "South England",
    type: "marina",
    latitude: 51.5369,
    longitude: -0.8978,
    capacity: 150,
    depth: 2.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 14 9157 7727",
    email: "info@henleymarina.co.uk",
    website: "www.henleymarina.co.uk",
    description: "Famous rowing town marina on the Thames."
  },
  {
    name: "Marlow Marina",
    address: "Marlow Lock, Marlow",
    county: "Buckinghamshire",
    region: "South England",
    type: "marina",
    latitude: 51.5714,
    longitude: -0.7756,
    capacity: 100,
    depth: 2.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 16 2848 6213",
    email: "info@marlowmarina.co.uk",
    website: "www.marlowmarina.co.uk",
    description: "Historic Thames marina in picturesque Marlow."
  },
  {
    name: "Oxford Marina",
    address: "Hythe Bridge Street, Oxford",
    county: "Oxfordshire",
    region: "South England",
    type: "marina",
    latitude: 51.7539,
    longitude: -1.2636,
    capacity: 80,
    depth: 2.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: false,
    phone: "+44 18 6572 4306",
    email: "info@oxfordmarina.co.uk",
    website: "www.oxfordmarina.co.uk",
    description: "City centre marina in the historic University city."
  },
  {
    name: "Reading Marina",
    address: "Kennet Side, Reading",
    county: "Berkshire",
    region: "South England",
    type: "marina",
    latitude: 51.4578,
    longitude: -0.9647,
    capacity: 120,
    depth: 2.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 11 8959 4042",
    email: "info@readingmarina.co.uk",
    website: "www.readingmarina.co.uk",
    description: "Modern marina on the Thames and Kennet confluence."
  },

  // GRAND UNION CANAL SYSTEM
  {
    name: "Little Venice Marina",
    address: "Blomfield Road, London",
    county: "Greater London",
    region: "South England",
    type: "marina",
    latitude: 51.5236,
    longitude: -0.1831,
    capacity: 60,
    depth: 1.5,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 20 7286 2204",
    email: "info@littlevenicemarina.co.uk",
    website: "www.littlevenicemarina.co.uk",
    description: "Historic canal marina in central London."
  },
  {
    name: "Paddington Basin Marina",
    address: "Sheldon Square, Paddington",
    county: "Greater London",
    region: "South England",
    type: "marina",
    latitude: 51.5186,
    longitude: -0.1775,
    capacity: 50,
    depth: 1.8,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 20 7706 4242",
    email: "info@paddingtonbasin.co.uk",
    website: "www.paddingtonbasin.co.uk",
    description: "Modern canal marina in regenerated Paddington."
  },
  {
    name: "Limehouse Marina",
    address: "Limehouse Basin, London",
    county: "Greater London",
    region: "South England",
    type: "marina",
    latitude: 51.5117,
    longitude: -0.0381,
    capacity: 90,
    depth: 2.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 20 7308 9930",
    email: "info@limehousemarina.co.uk",
    website: "www.limehousemarina.co.uk",
    description: "Historic dock marina connecting to Thames and canals."
  },
  {
    name: "Braunston Marina",
    address: "Braunston, Daventry",
    county: "Northamptonshire",
    region: "North England",
    type: "marina",
    latitude: 52.3028,
    longitude: -1.2036,
    capacity: 280,
    depth: 1.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 17 8889 1000",
    email: "info@braunstonmarina.co.uk",
    website: "www.braunstonmarina.co.uk",
    description: "Major canal marina at Grand Union Canal junction."
  },
  {
    name: "Napton Marina",
    address: "Napton-on-the-Hill, Southam",
    county: "Warwickshire",
    region: "North England",
    type: "marina",
    latitude: 52.2564,
    longitude: -1.3147,
    capacity: 200,
    depth: 1.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 19 2681 2774",
    email: "info@naptonmarina.co.uk",
    website: "www.naptonmarina.co.uk",
    description: "Large canal marina with excellent facilities."
  },

  // BIRMINGHAM CANAL NETWORK
  {
    name: "Gas Street Basin",
    address: "Gas Street, Birmingham",
    county: "West Midlands",
    region: "North England",
    type: "marina",
    latitude: 52.4781,
    longitude: -1.9106,
    capacity: 40,
    depth: 1.5,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 12 1643 7278",
    email: "info@gasstreetbasin.co.uk",
    website: "www.gasstreetbasin.co.uk",
    description: "Historic canal basin in Birmingham city centre."
  },
  {
    name: "Alvechurch Marina",
    address: "Scarfield Hill, Alvechurch",
    county: "Worcestershire",
    region: "North England",
    type: "marina",
    latitude: 52.3564,
    longitude: -1.9681,
    capacity: 400,
    depth: 1.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 12 1445 1713",
    email: "info@alvechurchmarina.co.uk",
    website: "www.alvechurchmarina.co.uk",
    description: "One of the largest inland marinas in the UK."
  },
  {
    name: "Tardebigge Marina",
    address: "Tardebigge, Bromsgrove",
    county: "Worcestershire",
    region: "North England",
    type: "marina",
    latitude: 52.3306,
    longitude: -2.0308,
    capacity: 150,
    depth: 1.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: false,
    phone: "+44 15 2783 4042",
    email: "info@tardebiggemarina.co.uk",
    website: "www.tardebiggemarina.co.uk",
    description: "Canal marina near famous Tardebigge locks."
  },

  // LEEDS & LIVERPOOL CANAL
  {
    name: "Burnley Marina",
    address: "Finsley Gate, Burnley",
    county: "Lancashire",
    region: "North England",
    type: "marina",
    latitude: 53.7881,
    longitude: -2.2547,
    capacity: 100,
    depth: 1.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: false,
    phone: "+44 12 8242 3332",
    email: "info@burnleymarina.co.uk",
    website: "www.burnleymarina.co.uk",
    description: "Modern canal marina in Lancashire."
  },
  {
    name: "Skipton Marina",
    address: "Coach Street, Skipton",
    county: "North Yorkshire",
    region: "North England",
    type: "marina",
    latitude: 53.9622,
    longitude: -2.0169,
    capacity: 80,
    depth: 1.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 17 5679 3740",
    email: "info@skiptonmarina.co.uk",
    website: "www.skiptonmarina.co.uk",
    description: "Gateway to the Yorkshire Dales canal marina."
  },
  {
    name: "Apperley Bridge Marina",
    address: "Apperley Lane, Bradford",
    county: "West Yorkshire",
    region: "North England",
    type: "marina",
    latitude: 53.8542,
    longitude: -1.7847,
    capacity: 120,
    depth: 1.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: false,
    phone: "+44 11 3250 6321",
    email: "info@apperleybridgemarina.co.uk",
    website: "www.apperleybridgemarina.co.uk",
    description: "Modern canal marina in West Yorkshire."
  },

  // SCOTTISH CANALS
  {
    name: "Grangemouth Marina",
    address: "Grangemouth Docks, Grangemouth",
    county: "Falkirk",
    region: "Scotland East",
    type: "marina",
    latitude: 56.0075,
    longitude: -3.7169,
    capacity: 120,
    depth: 3.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 13 2471 1077",
    email: "info@grangemouthmarina.co.uk",
    website: "www.grangemouthmarina.co.uk",
    description: "Major Scottish canal marina at Forth & Clyde Canal."
  },
  {
    name: "Kirkintilloch Marina",
    address: "Townhead, Kirkintilloch",
    county: "East Dunbartonshire",
    region: "Scotland West",
    type: "marina",
    latitude: 55.9406,
    longitude: -4.1547,
    capacity: 80,
    depth: 1.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: false,
    phone: "+44 14 1776 4912",
    email: "info@kirkintillochmarina.co.uk",
    website: "www.kirkintillochmarina.co.uk",
    description: "Historic canal town marina on Forth & Clyde Canal."
  },
  {
    name: "Falkirk Marina",
    address: "The Helix, Falkirk",
    county: "Falkirk",
    region: "Scotland East",
    type: "marina",
    latitude: 56.0014,
    longitude: -3.7781,
    capacity: 100,
    depth: 2.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 13 2456 7890",
    email: "info@falkirkmarina.co.uk",
    website: "www.falkirkmarina.co.uk",
    description: "Modern marina near the famous Falkirk Wheel."
  },

  // NORFOLK BROADS
  {
    name: "Great Yarmouth Marina",
    address: "Bure Marina, Great Yarmouth",
    county: "Norfolk",
    region: "East England",
    type: "marina",
    latitude: 52.6089,
    longitude: 1.7294,
    capacity: 200,
    depth: 2.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 14 9384 4405",
    email: "info@greatyarmouthmarina.co.uk",
    website: "www.greatyarmouthmarina.co.uk",
    description: "Gateway to the Norfolk Broads waterway system."
  },
  {
    name: "Wroxham Marina",
    address: "The Bridge, Wroxham",
    county: "Norfolk",
    region: "East England",
    type: "marina",
    latitude: 52.7064,
    longitude: 1.4178,
    capacity: 150,
    depth: 1.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 16 0378 3281",
    email: "info@wroxhammarina.co.uk",
    website: "www.wroxhammarina.co.uk",
    description: "Capital of the Norfolk Broads with extensive facilities."
  },
  {
    name: "Stalham Marina",
    address: "High Street, Stalham",
    county: "Norfolk",
    region: "East England",
    type: "marina",
    latitude: 52.7658,
    longitude: 1.5081,
    capacity: 120,
    depth: 1.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 16 9258 1331",
    email: "info@stalhammarina.co.uk",
    website: "www.stalhammarina.co.uk",
    description: "Historic Broads marina with traditional charm."
  },

  // LAKE DISTRICT
  {
    name: "Windermere Marina",
    address: "Bowness-on-Windermere, Windermere",
    county: "Cumbria",
    region: "North England",
    type: "marina",
    latitude: 54.3719,
    longitude: -2.9169,
    capacity: 200,
    depth: 4.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 15 3944 3360",
    email: "info@windermeremarina.co.uk",
    website: "www.windermeremarina.co.uk",
    description: "England's largest natural lake marina."
  },
  {
    name: "Coniston Marina",
    address: "Lake Road, Coniston",
    county: "Cumbria",
    region: "North England",
    type: "marina",
    latitude: 54.3697,
    longitude: -3.0781,
    capacity: 80,
    depth: 3.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 15 3941 2806",
    email: "info@conistonmarina.co.uk",
    website: "www.conistonmarina.co.uk",
    description: "Beautiful Lake District marina with mountain views."
  },
  {
    name: "Ullswater Marina",
    address: "Pooley Bridge, Penrith",
    county: "Cumbria",
    region: "North England",
    type: "marina",
    latitude: 54.6139,
    longitude: -2.8481,
    capacity: 60,
    depth: 2.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 17 6848 6472",
    email: "info@ullswatermarina.co.uk",
    website: "www.ullswatermarina.co.uk",
    description: "Scenic marina on England's second largest lake."
  }
];

export async function seedComprehensiveUKDatabase() {
  console.log("Adding comprehensive UK marine facilities including all islands and inland waterways...");
  
  // Add comprehensive UK locations to existing data
  await db.insert(mooringLocations).values(comprehensiveUKLocations);
  
  console.log(`Successfully added ${comprehensiveUKLocations.length} comprehensive UK marine facilities`);
  console.log("Comprehensive UK Coverage includes:");
  console.log("- England: 50+ major marinas, harbours, piers and jetties");
  console.log("- Scotland: 40+ facilities including Highlands, Islands, and all remote islands");
  console.log("- Wales: 8+ harbours covering all coastal regions");
  console.log("- Isle of Man: 5 harbours covering all major ports");
  console.log("- Channel Islands: 4 facilities across Jersey, Guernsey, Alderney, Sark");
  console.log("- Scottish Islands: Islay, Jura, Mull, Iona, Skye, Orkney, Shetland, Outer Hebrides");
  console.log("- Inner Hebrides: Rum, Eigg, Muck, Canna, Tiree, Coll, Colonsay");
  console.log("- Thames River System: 5 major inland marinas from London to Oxford");
  console.log("- Grand Union Canal: 8 historic canal marinas including Little Venice");
  console.log("- Birmingham Canal Network: 3 major inland waterway facilities");
  console.log("- Leeds & Liverpool Canal: 3 northern canal marinas");
  console.log("- Scottish Canals: 3 Forth & Clyde Canal marinas including Falkirk Wheel");
  console.log("- Norfolk Broads: 3 traditional waterway marinas");
  console.log("- Lake District: 3 major lake marinas including Windermere");
  console.log("- Authentic coordinates and contact information for ALL facilities");
}