import { db } from "./db";
import { mooringLocations, type InsertMooringLocation } from "@shared/schema";

const seedLocations: InsertMooringLocation[] = [
  {
    name: "Dingle Marina",
    address: "Marina Road, Dingle",
    county: "Kerry",
    region: "Southwest",
    type: "marina",
    latitude: 52.140369,
    longitude: -10.272496,
    capacity: 45,
    depth: 3.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+353 66 915 2222",
    email: "marina@dinglemarina.ie",
    website: "www.dinglemarina.ie",
    description: "Full-service marina in the heart of Dingle town with excellent facilities."
  },
  {
    name: "Howth Marina",
    address: "Howth Harbour, Howth",
    county: "Dublin",
    region: "East Coast",
    type: "marina",
    latitude: 53.390556,
    longitude: -6.065833,
    capacity: 180,
    depth: 4.2,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+353 1 832 2252",
    email: "info@howthmarina.ie",
    website: "www.howthmarina.ie",
    description: "Premier marina facility in Dublin Bay with full services and amenities."
  },
  {
    name: "Ballycotton Pier",
    address: "Ballycotton Harbour, Ballycotton",
    county: "Cork",
    region: "South Coast",
    type: "pier",
    latitude: 51.825556,
    longitude: -7.984167,
    capacity: 12,
    depth: 2.8,
    hasFuel: false,
    hasWater: true,
    hasElectricity: false,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+353 21 464 6718",
    email: "harbourmaster@ballycotton.ie",
    website: "www.ballycottonharbour.ie",
    description: "Small fishing pier with basic facilities for visiting boats."
  },
  {
    name: "Kilmore Quay Jetty",
    address: "Kilmore Quay Harbour",
    county: "Wexford",
    region: "Southeast",
    type: "jetty",
    latitude: 52.173056,
    longitude: -6.585833,
    capacity: 8,
    depth: 2.1,
    hasFuel: false,
    hasWater: true,
    hasElectricity: false,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+353 53 912 9684",
    email: "info@kilmorequay.ie",
    website: "www.kilmorequayharbour.com",
    description: "Traditional fishing jetty with basic mooring facilities."
  },
  {
    name: "Galway Docks Marina",
    address: "New Dock Road, Galway",
    county: "Galway",
    region: "West Coast",
    type: "marina",
    latitude: 53.270833,
    longitude: -9.053611,
    capacity: 95,
    depth: 3.8,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: false,
    phone: "+353 91 561 874",
    email: "marina@galwaydocks.ie",
    website: "www.galwaydocks.ie",
    description: "Modern marina in Galway city with excellent access to the city center."
  },
  {
    name: "Belfast Marina",
    address: "Sydenham Road, Belfast",
    county: "Antrim",
    region: "North Coast",
    type: "marina",
    latitude: 54.602778,
    longitude: -5.890556,
    capacity: 120,
    depth: 4.0,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 28 9073 7368",
    email: "info@belfastmarina.com",
    website: "www.belfastmarina.com",
    description: "State-of-the-art marina facility in Belfast Lough."
  },
  {
    name: "Kinsale Marina",
    address: "Pier Road, Kinsale",
    county: "Cork",
    region: "South Coast",
    type: "marina",
    latitude: 51.707222,
    longitude: -8.530556,
    capacity: 75,
    depth: 3.2,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+353 21 477 4959",
    email: "marina@kinsale.ie",
    website: "www.kinsalemarina.ie",
    description: "Beautiful marina in the historic town of Kinsale."
  },
  {
    name: "Dunmore East Pier",
    address: "Harbour Road, Dunmore East",
    county: "Waterford",
    region: "Southeast",
    type: "pier",
    latitude: 52.150278,
    longitude: -6.995833,
    capacity: 15,
    depth: 2.5,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+353 51 383 166",
    email: "harbour@dunmoreeast.ie",
    website: "www.dunmoreeastharbour.com",
    description: "Picturesque fishing pier with good shelter and basic facilities."
  },
  {
    name: "Killybegs Marina",
    address: "Harbour Road, Killybegs",
    county: "Donegal",
    region: "Northwest",
    type: "marina",
    latitude: 54.631667,
    longitude: -8.448333,
    capacity: 40,
    depth: 4.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: false,
    phone: "+353 74 973 1518",
    email: "marina@killybegsport.ie",
    website: "www.killybegsport.ie",
    description: "Ireland's premier fishing port with excellent facilities for visiting yachts."
  },
  {
    name: "Bundoran Marina",
    address: "Harbour View, Bundoran",
    county: "Donegal",
    region: "Northwest",
    type: "marina",
    latitude: 54.478056,
    longitude: -8.283611,
    capacity: 25,
    depth: 3.0,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+353 71 984 1350",
    email: "marina@bundorantourism.ie",
    website: "www.bundoranmarina.ie",
    description: "Scenic marina in the popular seaside resort town of Bundoran."
  },
  {
    name: "Rathmullan Pier",
    address: "Pier Road, Rathmullan",
    county: "Donegal",
    region: "Northwest",
    type: "pier",
    latitude: 55.095833,
    longitude: -7.533056,
    capacity: 12,
    depth: 2.8,
    hasFuel: false,
    hasWater: true,
    hasElectricity: false,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+353 74 915 8188",
    email: "pier@rathmullan.ie",
    website: "www.rathmullanharbour.com",
    description: "Historic pier on Lough Swilly with beautiful mountain views."
  },
  {
    name: "Bangor Marina",
    address: "Marina Road, Bangor",
    county: "Down",
    region: "North Coast",
    type: "marina",
    latitude: 54.665278,
    longitude: -5.668056,
    capacity: 280,
    depth: 4.2,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 28 9145 3297",
    email: "info@bangormarina.com",
    website: "www.bangormarina.com",
    description: "Award-winning marina facility in Belfast Lough with comprehensive services."
  },
  {
    name: "Carrickfergus Marina",
    address: "Marine Highway, Carrickfergus",
    county: "Antrim",
    region: "North Coast",
    type: "marina",
    latitude: 54.715833,
    longitude: -5.806944,
    capacity: 300,
    depth: 3.8,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: true,
    phone: "+44 28 9336 6666",
    email: "marina@carrickfergus.org",
    website: "www.carrickfergusmarina.co.uk",
    description: "Large modern marina near historic Carrickfergus Castle."
  },
  {
    name: "Ballycastle Harbour",
    address: "The Harbour, Ballycastle",
    county: "Antrim",
    region: "North Coast",
    type: "pier",
    latitude: 55.206944,
    longitude: -6.235278,
    capacity: 18,
    depth: 2.5,
    hasFuel: false,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+44 28 2076 2024",
    email: "harbour@ballycastle.gov.uk",
    website: "www.ballycastleharbour.com",
    description: "Traditional fishing harbour on the famous Causeway Coast."
  },
  {
    name: "Coleraine Marina",
    address: "Marina Road, Coleraine",
    county: "Londonderry",
    region: "North Coast",
    type: "marina",
    latitude: 55.132778,
    longitude: -6.668056,
    capacity: 50,
    depth: 3.5,
    hasFuel: true,
    hasWater: true,
    hasElectricity: true,
    hasWasteDisposal: true,
    hasShowers: true,
    hasRestaurant: false,
    phone: "+44 28 7034 4768",
    email: "marina@coleraine.gov.uk",
    website: "www.colerainemarina.co.uk",
    description: "River marina on the Lower Bann with good access to the north coast."
  },
  {
    name: "Greencastle Pier",
    address: "Pier Road, Greencastle",
    county: "Donegal",
    region: "Northwest",
    type: "pier",
    latitude: 55.199167,
    longitude: -6.998333,
    capacity: 8,
    depth: 2.2,
    hasFuel: false,
    hasWater: true,
    hasElectricity: false,
    hasWasteDisposal: false,
    hasShowers: false,
    hasRestaurant: false,
    phone: "+353 74 938 1049",
    email: "greencastle@donegalcoco.ie",
    website: "www.greencastlepier.ie",
    description: "Small fishing pier at the mouth of Lough Foyle."
  }
];

async function seedDatabase() {
  try {
    console.log("Starting database seeding...");
    
    // Import and run comprehensive seeding for all Irish marine facilities
    const { seedComprehensiveDatabase } = await import('./comprehensive-seed');
    await seedComprehensiveDatabase();
    
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}

export { seedDatabase };